In [2]:
import numpy as np
import imageio

In [57]:
#1. Подсчитать  произведение ненулевых элементов на диагонали прямоугольной матрицы.
#Функция
def notNullDiag(arr):
    mul = 1
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if i == j:
                if arr[i][j] != 0:
                    mul *= arr[i][j]
    return mul#1. Подсчитать  произведение ненулевых элементов на диагонали прямоугольной матрицы.
#Функция
def notNullDiag(arr):
    mul = 1
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            if i == j:
                if arr[i][j] != 0:
                    mul *= arr[i][j]
    return mul

hundred = np.random.randint(1000, size=(100,90))
thousand = np.random.randint(10000, size=(1000,900))
tenThousand = np.random.randint(100000, size=(10000,9000))

print("For hundred: ")
%timeit notNullDiag(hundred)
print("For thousand:")
%timeit notNullDiag(thousand)
print("For ten thousand:")
%timeit notNullDiag(tenThousand)


In [ ]:
#2. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).
#Функция

def secondTask(x, i, j):
    vector = np.zeros(i.size, dtype=int)
    for k in range(i.size):
        vector[k] = x[i[k],j[k]]
    return vector

X = np.random.randint(1000, size=(100,100))
iHundred = np.random.randint(100, size=100)
jHundred = np.random.randint(100, size=100)

iThousand = np.random.randint(100, size=1000)
jThousand = np.random.randint(100, size=1000)

iTenThousand = np.random.randint(100, size=10000)
jTenThousand = np.random.randint(100, size=10000)

%timeit secondTask(X, iHundred, jHundred)
%timeit secondTask(X, iThousand, jThousand)
%timeit secondTask(X, iTenThousand, jTenThousand)

In [85]:
#3. Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
#Функция

def isMultiset(arr1, arr2):
    isMul = True
    if arr1.size == arr2.size:
        for i in range(arr1.size):
            if arr1[arr1 == arr1[i]].size != arr2[arr2 == arr1[i]].size:
                isMul = False
                break
    else:
        isMul = False
    return isMul

#3.Тесты
hundredX = np.random.randint(0, 1, 100)
hundredY = np.random.randint(0, 1, 100)

thousandX = np.random.randint(0, 1, 1000)
thousandY = np.random.randint(0, 1, 1000)

tenThousandX = np.random.randint(0, 1, 10000)
tenThousandY = np.random.randint(0, 1, 10000)

%timeit isMultiset(hundredX, hundredY)
%timeit isMultiset(thousandX, thousandY)
%timeit isMultiset(tenThousandX, tenThousandY)

327 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.77 ms ± 40.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
223 ms ± 3.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
#4. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.
#Функция

def fourTask(arr):
    max = 0
    for i in range(1, arr.size):
        if arr[i-1] == 0:
            if arr[i] > max:
                max = arr[i]
    return max

#4.Тесты
hundred = np.random.randint(1000, size=100)
thousand = np.random.randint(10000, size=1000)
tenThousand = np.random.randint(100000, size=10000)

%timeit fourTask(hundred)
%timeit fourTask(thousand)
%timeit fourTask(tenThousand)

19.6 µs ± 382 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
208 µs ± 4.05 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.14 ms ± 30 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [131]:
#5.1

def imageTask(img, weights):
    imageReturn = np.zeros((img.shape[1], img.shape[2]))
    image = np.zeros((img.shape[1], img.shape[2]))
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            for k in range(img.shape[2]):
                image[j, k] = img[i, j, k]*weights[i]
        imageReturn += image
    return imageReturn

imageBig = imageio.imread('big.jpg').transpose(2,0,1)
imageMiddle = imageio.imread('small.jpg').transpose(2,0,1)
imageSmall = imageio.imread('middle.jpg').transpose(2,0,1)
weights = np.array([0.299, 0.587, 0.114])

%timeit imageTask(imageSmall, weights)
%timeit imageTask(imageMiddle, weights)
%timeit imageTask(imageBig, weights)


336 ms ± 19.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
498 ms ± 33.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.07 s ± 293 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [86]:
#6. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.

def runLength(arr):
    uniq = np.array(np.unique(arr))
    runLengthEncoding = (uniq,uniq)
    for i in range(uniq.size):
        size = arr[arr == uniq[i]].size
        runLengthEncoding[0][i] = uniq[i]
        runLengthEncoding[1][i] = size
    return runLengthEncoding

hundred6 = np.random.randint(1000, size=100)
thousand6 = np.random.randint(10000, size=1000)
tenThousand6 = np.random.randint(100000, size=10000)

%timeit runLength(hundred6)
%timeit runLength(thousand6)
%timeit runLength(tenThousand6)

185 µs ± 717 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
2.47 ms ± 27.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
59.7 ms ± 778 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [133]:
#7. Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравнить с функцией scipy.spatial.distance.cdist.

def euclid(x, y):
    arr = np.zeros((x.size, x.size))
    for i in range(x.size):
        for j in range(x.size):
            arr[i,j] = np.sqrt( np.square(x[j] - x[i]) + np.square(y[j] - y[i]))
    return arr

hundredX = np.random.randint(100, size=100)
hundredY = np.random.randint(100, size=100)

hundredX = np.arange(4)
hundredY = np.arange(4)

thousandX = np.random.randint(100, size=1000)
thousandY = np.random.randint(100, size=1000)

tenThousandX = np.random.randint(100, size=10000)
tenThousandY = np.random.randint(100, size=10000)

%timeit euclid(hundredX, hundredY)
%timeit euclid(thousandX, thousandY)
%timeit euclid(tenThousandX, tenThousandY)

[[0.         1.41421356 2.82842712 4.24264069]
 [1.41421356 0.         1.41421356 2.82842712]
 [2.82842712 1.41421356 0.         1.41421356]
 [4.24264069 2.82842712 1.41421356 0.        ]]
58.5 µs ± 719 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.67 s ± 157 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


KeyboardInterrupt: 