In [80]:
import numpy as np
import imageio
import numpy.linalg
from scipy.spatial import distance_matrix

In [50]:
#1. Подсчитать  произведение ненулевых элементов на диагонали прямоугольной матрицы.

def notNullDiag(arr):
    diag = arr.diagonal()
    mul = 1
    for i in diag:
        if i != 0:
            mul *= i
    return mul

hundred = np.random.randint(1000, size=(100,90))
thousand = np.random.randint(10000, size=(1000,900))
tenThousand = np.random.randint(100000, size=(10000,9000))

print("For hundred: ")
%timeit notNullDiag(hundred)
print("For thousand:")
%timeit notNullDiag(thousand)
print("For ten thousand:")
%timeit notNullDiag(tenThousand)

For hundred: 


/var/folders/04/7ltt_n9d1z14zmw8_ky4jc5h0000gn/T/ipykernel_81635/479424540.py:8: RuntimeWarning: overflow encountered in long_scalars
  mul *= i


55.6 µs ± 844 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
For thousand:
261 µs ± 770 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
For ten thousand:
2.53 ms ± 788 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [85]:
#2. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).

def secondTask(X, i, j):
    arr = np.zeros_like(i)
    arr = X[i, j]
    return arr


X = np.random.randint(1000, size=(100,100))

iHundred = np.random.randint(100, size=100)
jHundred = np.random.randint(100, size=100)

iThousand = np.random.randint(100, size=1000)
jThousand = np.random.randint(100, size=1000)

iTenThousand = np.random.randint(100, size=10000)
jTenThousand = np.random.randint(100, size=10000)

%timeit secondTask(X, iHundred, jHundred)
%timeit secondTask(X, iThousand, jThousand)
%timeit secondTask(X, iTenThousand, jTenThousand)




4.52 µs ± 43.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
8.41 µs ± 344 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
41.3 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [51]:
#3. Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
x = np.array([1, 2, 2, 4, 3, 1, 7])
y = np.array([4, 2, 2, 1, 3, 7, 1])


def isMultiset(x, y):
    isMul = True
    if x.size == y.size:
        for i in range(x.size):
            if np.where(y==x[i])[0].size != 0:
                index = np.where(y==x[i])[0][0]
                np.delete(y,index)
            else:
                isMul = False
    else:
        isMul = False


#3.3.Тесты
hundredX = np.random.randint(0, 1, 100)
hundredY = np.random.randint(0, 1, 100)

thousandX = np.random.randint(0, 1, 1000)
thousandY = np.random.randint(0, 1, 1000)

tenThousandX = np.random.randint(0, 1, 10000)
tenThousandY = np.random.randint(0, 1, 10000)

%timeit isMultiset(hundredX, hundredY)
%timeit isMultiset(thousandX, thousandY)
%timeit isMultiset(tenThousandX, tenThousandY)

905 µs ± 5.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12.1 ms ± 94.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
316 ms ± 13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
#4. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.

def fourTask(x):
    vector = np.zeros_like(x)
    for i in range(1, x.size):
        if x[i-1] == 0:
            vector[i] = x[i]
    return vector.max()

#4.Тесты
hundred = np.random.randint(1000, size=100)
thousand = np.random.randint(10000, size=1000)
tenThousand = np.random.randint(100000, size=10000)

%timeit fourTask(hundred)
%timeit fourTask(thousand)
%timeit fourTask(tenThousand)

24.9 µs ± 260 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
225 µs ± 3.26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.2 ms ± 28.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [74]:
#5.3
def imageTask(img, weights):
    imageReturn = np.zeros((img.shape[1], img.shape[2]))
    for i in range(img.shape[0]):
        imageReturn += img[i]*weights[i]
    return imageReturn

imageBig = imageio.imread('big.jpg').transpose(2,0,1)
imageMiddle = imageio.imread('small.jpg').transpose(2,0,1)
imageSmall = imageio.imread('middle.jpg').transpose(2,0,1)
weights = np.array([0.299, 0.587, 0.114])

%timeit imageTask(imageSmall, weights)
%timeit imageTask(imageMiddle, weights)
%timeit imageTask(imageBig, weights)


95.1 µs ± 758 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


KeyboardInterrupt: 

In [53]:
#6. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.

def runLength(x):
    numbersSet = set()
    for i in range(x.size):
        numbersSet.add(x[i])
    repeats = np.zeros(len(numbersSet), dtype=int)
    numbers = np.array(list(numbersSet))

    for i in range(numbers.size):
        repeats[i] = np.where(x == numbers[i])[0].size

    tuple = (numbers, repeats)
    return tuple

hundred6 = np.random.randint(1000, size=100)
thousand6 = np.random.randint(10000, size=1000)
tenThousand6 = np.random.randint(100000, size=10000)

%timeit runLength(hundred6)
%timeit runLength(thousand6)
%timeit runLength(tenThousand6)


231 µs ± 8.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.92 ms ± 38.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
65.4 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [84]:
#7.3

def euclid(x, y):
    points = np.zeros((x.size, 2))
    for i in range(x.size):
        points[i, 0] = x[i]
        points[i, 1] = y[i]
    euclideanMatrix = np.zeros((x.size, x.size))
    for i in range(x.size):
        for j in range(x.size):
            euclideanMatrix[i,j] = np.linalg.norm(points[i] - points[j])
    return distance_matrix(points, points)



hundredX = np.random.randint(100, size=100)
hundredY = np.random.randint(100, size=100)

thousandX = np.random.randint(100, size=1000)
thousandY = np.random.randint(100, size=1000)

tenThousandX = np.random.randint(100, size=10000)
tenThousandY = np.random.randint(100, size=10000)

%timeit euclid(hundredX, hundredY)
%timeit euclid(thousandX, thousandY)
%timeit euclid(tenThousandX, tenThousandY)

[[0.         1.41421356 2.82842712 4.24264069]
 [1.41421356 0.         1.41421356 2.82842712]
 [2.82842712 1.41421356 0.         1.41421356]
 [4.24264069 2.82842712 1.41421356 0.        ]]


KeyboardInterrupt: 